### ISSUE TITLE
Ical link has wrong time zone

### ISSUE THREAD

**Issue by Kahevajo** [datasektionen/pandora#10]
We tried to book a time for 13-17 but in the ical calendar it was 14-18 instead. Probably wrong time zone or does not account for summer and winter time.

**Comment by jonasdahl** [comment]
Is this event still in the calendar? Which was the date/time? @Kahevajo

**Comment by Kahevajo** [comment]
It was in the calendar at bokning.datasektionen.se but it seems to be missing now. In the ical-calender we can see that it is booked 14-18 but in the email that we got and on the site before we specified 13-17.

**Comment by jonasdahl** [comment]
Ah I see! I will look into it :)

**Comment by Kahevajo** [comment]
<img width="95" alt="screen shot 2016-12-08 at 21 32 28" src="https://cloud.githubusercontent.com/assets/5826079/21026664/facaa926-bd8d-11e6-80f8-494337e17cf8.png">
<img width="614" alt="screen shot 2016-12-08 at 21 32 51" src="https://cloud.githubusercontent.com/assets/5826079/21026665/facd9da2-bd8d-11e6-809e-ee57ebeb334e.png">

Here are two pictures also. We managed to pick the wrong monday first and then changed it, but with the same time.

**Comment by jonasdahl** [comment]
Then it is the export from the database to iCal that is screwed up! Thanks for the pic!

**Comment by jonasdahl** [comment]
Should be fixed now, but since Google caches calendars for 24-48 hours it might not be immediately visible.

Here is a short video to watch while waiting: https://www.youtube.com/watch?v=G9Y5Dhzciyc
🍿
