### ISSUE TITLE
Året blir fel när kalendern slå över.

### ISSUE THREAD

**Issue by simonedeblasio** [datasektionen/pandora#19]
Tex när man är på vecka 52 2018 så kommer vecka 1 2018 efter, istället för vecka 1 2019.

**Comment by simonedeblasio** [comment]
@bullfest

**Comment by jonasdahl** [comment]
Om någon vill fixa så är det förmodligen här man bör göra det: https://github.com/datasektionen/pandora/blob/master/app/Http/Controllers/EntityController.php#L99

Alternativa lösningar:
- Vänta till efter 1 januari så att ingen märker igen förrän om typ 7 år eller så (och då är hela systemet förhoppningsvis utbytt)
- Inför en datasektioniansk kalender som definieras av Pandora (Pandoras kalender). Eftersom rekursion uppstår kommer ingen åldras. Dåligt eftersom man då kommer ha svårt att påstå att det var bättre förr.
- Gör en if-sats som kollar om året är 2018 och då ökar med 1. (Inte så hållbart eftersom man måste hålla reda på att man inte ökar med tex 2)
- Byta ut kalenderimplementationen mot en databas där dsys åläggs lägga till varje år typ en gång om året. Dock problematiskt om dsys, gud förbjude, vakantsätts. Då kommer ingen ny dsys kunna väljas pga att ett nytt SM inte kan hållas pga att tiden står still.
- Ett webbläsarplugin som automatiskt redirectar till rätt sida. Kan dock kräva onödigt mycket arbete då Internet Explorers extensionstöd är otroligt knapert för tidiga versioner.
- Förbjuda sektionsaktiva att blicka framåt. Endast förr var det bättre och så kommer det alltid att vara. Krävs dock ett SM och då är 2019 redan här. 😱😱😱😱
- Göra en popup som informerar om felet och instruerar användaren hur man ändrar i urlen för att komma framåt i tiden. Kan dock innebära att man måste lägga tid på att kringgå Chromes popupskydd, i övrigt inga nackdelar.
Öppen för andra förslag också!

Själv kanske jag har tid att fixa något av ovanstående först under julhelgen men om någon annan vill fixa så är det bara att köra!

**Comment by bullfest** [comment]
This is known, men det funkar om man ändrar i url:en, och som Jonas säger så kommer det inte spela roll föränn om 7 år igen... så ¯\_(ツ)_/¯

Få @datasektionen/d-rektoratet  att utfärda ett d-rektiv om att det alltid kommer vara 2018.

**Comment by oskstr** [comment]
<img width="310" alt="bokning" src="https://user-images.githubusercontent.com/23638900/50483123-92b76300-09ea-11e9-9c44-d714fb71dce7.png">

URLn verkar också allmänt vara lite väl snäll med vad som tillåts. Kanske inte särskilt stort problem dock.

**Comment by oskstr** [comment]
Jag läste på lite om hur ISO-veckor fungerar och det verkar som att året som en vecka ligger i bestäms av var torsdagen ligger, är det inte bara ändra på raden till 
```js
->with('nextYear', date("Y", strtotime("+1week thursday", $startDate)))
```
?
