### ISSUE TITLE
Ändra ordning på bokningsentiteter

### ISSUE THREAD

**Issue by CarlB04** [datasektionen/pandora#46]
Föreslagen ordning
Övre raden: META -> Mötesrummet -> Lusen -> Cerise
Nedre raden: Filmkamera -> Tag Monkeys Kamera -> LoL grejer -> GoPro

**Comment by Karl-Isac** [comment]
Ey! Jag löste det :)
Nu går det att ge entiteter ett värde mellan 1-100 som de sorteras efter ^-^
